test: linked_list.c linked_list.h stack.c stack.h graph.c graph.h queue.c queue.h dynamic_array.c dynamic_array.h binary_heap.c binary_heap.h union_find.c union_find.h main.c
	gcc linked_list.c linked_list.h stack.h stack.c graph.c graph.h queue.c queue.h dynamic_array.c dynamic_array.h binary_heap.c binary_heap.h union_find.c union_find.h main.c -o test -g
